name: flutter_firebase_chatapp
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^2.32.0
  cloud_firestore: ^4.17.4
  firebase_storage: ^11.7.6
  intl: ^0.19.0
  image_picker: ^1.1.1
  firebase_auth: ^4.19.6
  google_sign_in: ^6.2.1
  firebase_database: ^10.5.7
  file_picker: ^8.0.5
  fluttertoast: ^8.2.6
  flutter_pdfview: ^1.3.2
  url_launcher: ^6.3.0


  # 
  dash_chat_2: ^0.0.20
  firebase_analytics: ^10.8.10
  google_fonts: ^6.2.1
  delightful_toast: ^1.1.0
  get_it: ^7.6.7
  path: ^1.9.0
  get: ^4.6.6
  flutter_screenutil: 5.9.3
  dots_indicator: ^3.0.0
  package_info_plus: ^8.0.1
  shared_preferences: ^2.3.1
  cached_network_image: ^3.4.0
  equatable: ^2.0.5
  bloc: ^8.1.4
  json_annotation: ^4.9.0
  flutter_bloc: ^8.1.6
  go_router: ^13.2.5
  hydrated_bloc: ^9.1.5
  scrollable_positioned_list: ^0.3.8
  inview_notifier_list:
    git: https://github.com/Gambley1/inview_notifier_list
  animations: ^2.0.11
  fast_immutable_collections: ^10.2.4
  palette_generator: ^0.3.3+4
  story_view: ^0.16.5
  flutter_staggered_grid_view: ^0.7.0
  sliver_tools: ^0.2.12
  slang_flutter: ^3.31.0
  slang: ^3.31.1
  lottie: ^3.1.2
  flutter_localizations:
    sdk: flutter
  app_ui:
    path: packages/app_ui
  chats_repository:
    path: packages/chats_repository
  shared:
    path: packages/shared
  form_fields:
    path: packages/form_fields
  notifications_repository:
    path: packages/notifications_repository
  supabase_authentication_client:
    path: packages/authentication_client/supabase_authentication_client
  firebase_notifications_client:
    path: packages/notifications_client/firebase_notifications_client


  persistent_storage:
    path: packages/storage/persistent_storage
  posts_repository:
    path: packages/posts_repository
  powersync_repository:
    path: packages/powersync_repository
  search_repository:
    path: packages/search_repository
  stories_editor:
    path: packages/stories_editor
  stories_repository:
    path: packages/stories_repository
  token_storage:
    path: packages/authentication_client/token_storage
  user_repository:
    path: packages/user_repository
  instagram_blocks_ui:
    path: packages/instagram_blocks_ui
  firebase_remote_config_repository:
    path: packages/firebase_remote_config_repository
  envied: ^0.5.4+1



dependency_overrides:
  fading_edge_scrollview: ^4.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.11
  slang_build_runner: ^3.31.0
  envied_generator: ^0.5.4+1

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/logo_LuxOasis.png
    - assets/default_avatar.png
    - assets/images/banner1.webp
    - assets/images/banner2.webp
    - assets/images/banner3.webp
    - assets/images/chat-icon.jpg
  # fonts:
  #   - family: Avenir
  #     fonts:
  #       - asset: assets/fonts/Avenir-Book.ttf
  #         weight: 400 # normal
  #   - family: Montserrat
  #     fonts:
  #       - asset: assets/fonts/Montserrat-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Montserrat-SemiBold.ttf
  #         weight: 600
  #   - family: Iconfont
  #     fonts:
  #       - asset: assets/fonts/iconfont.ttf
