// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBE2Hm1zZ4JQc3TrBB9aFKfLfIAQTJEfIo',
    appId: '1:856264269677:web:5cc9462a1315cf08680464',
    messagingSenderId: '856264269677',
    projectId: 'vuong-561c7',
    authDomain: 'vuong-561c7.firebaseapp.com',
    storageBucket: 'vuong-561c7.appspot.com',
    measurementId: 'G-ST3E2BHHZE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbkrStP4mM4DdKAPAD4ixCfveTMcMXqlc',
    appId: '1:577087706126:android:c32f659f63a48eb329185f',
    messagingSenderId: '577087706126',
    projectId: 'flutter-firebase-chatapp-4cddb',
    storageBucket: 'flutter-firebase-chatapp-4cddb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmruHQKHCk5hKeN5Owp_gqynPImVyhsN0',
    appId: '1:577087706126:ios:03ddfb3dd153ac8b29185f',
    messagingSenderId: '577087706126',
    projectId: 'flutter-firebase-chatapp-4cddb',
    storageBucket: 'flutter-firebase-chatapp-4cddb.appspot.com',
    iosBundleId: 'com.example.flutterFirebseProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzzul8qd6nxpIX9PBmls4BWJC53ntLO1w',
    appId: '1:856264269677:ios:91a99a709206f592680464',
    messagingSenderId: '856264269677',
    projectId: 'vuong-561c7',
    storageBucket: 'vuong-561c7.appspot.com',
    iosBundleId: 'com.example.flutterFirebseProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBE2Hm1zZ4JQc3TrBB9aFKfLfIAQTJEfIo',
    appId: '1:856264269677:web:cfced39e8dc9b6c3680464',
    messagingSenderId: '856264269677',
    projectId: 'vuong-561c7',
    authDomain: 'vuong-561c7.firebaseapp.com',
    storageBucket: 'vuong-561c7.appspot.com',
    measurementId: 'G-862YN8STHD',
  );
}