on:
    pull_request:
      branches:
        - main
        - master
    push:
      branches:
        - main
        - master
        - develop
    
name: "Build & Release"

jobs:
    build:
      name: Build & Release
      runs-on: macos-latest
      steps:
        - name: 🚀 Run actions/checkout@v2
          uses: actions/checkout@v2
        
        - name: 🚀 Run actions/setup-java@v1
          uses: actions/setup-java@v1
          with:
            java-version: '12.x'
        
        - name: 🚀 Run action/checkout@v3
          uses: actions/checkout@v3

        - name: 🚀 Install Flutter SDK
          uses: mobiledevops/flutter-sdk-action@v1.0.0
          with:
            flutter-sdk-version: 3.19.5
        
        - name: 🚀 Check flutter version.
          run: flutter --version
        
        - name: 🚀 Install dependencies.
          run: flutter pub get

        # - name: 🚀 Analyze project source
        #   run: dart analyze

        - name: 🚀 Build ios apk.
          run: flutter build apk --debug --split-per-abi
        - name: 🚀 Run build ios --no-codesign
          run: |
            flutter build ios --no-codesign
            cd build/ios/iphoneos
            mkdir Payload
            cd Payload
            ln -s ../Runner.app
            cd ..
            zip -r app.ipa Payload
        - name: 🚀 Push to Releases
          uses: ncipollo/release-action@v1
          with:
            artifacts: "build/app/outputs/apk/debug/*,build/ios/iphoneos/app.ipa"
            tag: v1.0.${{ github.run_number }}
            token: ${{ secrets.TOKEN_GITHUB }}

  
  
  
  
  # push to master, main, develop
  # pull request on main master
